### ISSUE TITLE
Fixing and finalizing window sets

### ISSUE THREAD

**Issue by jonch070** [rewgs/Reaify#2]

**Comment by rewgs** [comment]
Wrong repo :p Ours is here: https://github.com/rewgs/jonathan-kawchuk-reaper-template-and-pipeline

**Comment by jonch070** [comment]
Oh gotcha! Shall I move them over? Also can I somehow be an owner of our repo so I can add it in linear?

Jon

sound | composition
jonathankawchuk.com ( http://jonathankawchuk.com/ )

Sent via Superhuman ( ***@***.*** )
